# ---- Build Stage ----
FROM maven:3.9.6-eclipse-temurin-22-alpine AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

# ---- Runtime Stage ----
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

COPY --from=build /app/target/learning-path-app-1.0.0.jar /app/learning-path-app-1.0.0.jar 

CMD ["java","-jar","learning-path-app-1.0.0.jar"]